# Generated by Django 6.1.1 on 2026-10-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_reviewcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookattachment',
            options={'ordering': ['file_type', 'created_at'], 'verbose_name': 'Файл книги', 'verbose_name_plural': 'Файлы книг'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_page',
        ),
        migrations.AlterField(
            model_name='bookattachment',
            name='file',
            field=models.FileField(blank=True, upload_to='books/attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='bookattachment',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'MP3'), ('mp4', 'MP4'), ('ppt', 'PPT')], default='pdf', max_length=10, verbose_name='Тип файла'),
        ),
        migrations.AlterField(
            model_name='bookattachment',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
