# Generated by Django 6.1.1 on 2026-10-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_book_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookattachment',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('mp3', 'MP3'), ('mp4', 'MP4')], default='pdf', max_length=10, verbose_name='Тип файла'),
        ),
    ]
